package main.java.org.rashiktimalsina;

import main.java.org.rashiktimalsina.entities.Book;
import main.java.org.rashiktimalsina.entities.User;
import main.java.org.rashiktimalsina.entities.Transaction;
import main.java.org.rashiktimalsina.services.BookService;
import main.java.org.rashiktimalsina.services.BookServiceImpl;
import main.java.org.rashiktimalsina.services.TransactionService;
import main.java.org.rashiktimalsina.services.TransactionServiceImpl;
import main.java.org.rashiktimalsina.services.UserService;
import main.java.org.rashiktimalsina.services.UserServiceImpl;
import main.java.org.rashiktimalsina.utils.IdGenerator;

import java.time.LocalDate;
import java.util.List;
import java.util.Scanner;

/**
 * @author RashikTimalsina
 * @created 29/04/2025
 */

public class MyMainApp {
    //keeping the objects static as they will have only one instance for now
    private static BookService bookService = new BookServiceImpl();
    private static UserService userService = new UserServiceImpl();
    private static TransactionService transactionService = new TransactionServiceImpl(bookService);

    //create a scanner object to take input from the user(library manager)
    private static Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        while (true) {
            System.out.println("\n-----------------------------------------------");
            System.out.println("--- Welcome to Library Management System ---");
            System.out.println("-----------------------------------------------");
            System.out.println("1. Book Operations");
            System.out.println("2. User Operations");
            System.out.println("3. Transaction Operations");
            System.out.println("4. Exit");
            System.out.print("Enter your choice: ");

            int mainChoice = scanner.nextInt();
            scanner.nextLine(); // consume newline

            switch (mainChoice) {
                case 1:
                    bookOperations();
                    break;
                case 2:
                    userOperations();
                    break;
                case 3:
                    transactionOperations();
                    break;
                case 4:
                    System.out.println("Exiting system.");
                    System.exit(0);
                default:
                    System.out.println("Invalid choice. Try again.");
            }
        }
    }

    // BOOK OPERATIONS
    private static void bookOperations() {
        while (true) {
            System.out.println("\n--- Book Operations ---");
            System.out.println("1. Add Book");
            System.out.println("2. View All Books");
            System.out.println("3. Search by Title");
            System.out.println("4. Search by Author");
            System.out.println("5. View Available Books");
            System.out.println("6. Back to Main Menu");
            System.out.print("Enter choice: ");

            int choice = scanner.nextInt();
            scanner.nextLine();

            switch (choice) {
                case 1:
                    addNewBook();
                    break;
                case 2:
                    viewAllBooks();
                    break;
                case 3:
                    searchBookByTitle();
                    break;
                case 4:
                    searchBookByAuthor();
                    break;
                case 5:
                    viewAvailableBooks();
                    break;
                case 6:
                    return;
                default:
                    System.out.println("Invalid choice.");
            }
        }
    }

    private static void addNewBook() {
        System.out.print("Enter book title: ");
        String title = scanner.nextLine();
        System.out.print("Enter author: ");
        String author = scanner.nextLine();

        // creating a book object which consists of autogenerated-id , title and author as an args
        Book book = new Book(IdGenerator.generateBookId(), title, author);
        //adding the user object using add method defined inside userService class
        bookService.addBook(book);
        System.out.println("Book added: " + book);
    }

    private static void viewAllBooks() {
        //fetch all books in a list calling getAllBooks method of bookService
        List<Book> books = bookService.getAllBooks();
        //check if the list if empty
        if (books.isEmpty()) {
            System.out.println("No books found.");
        } else {
            // otherwise traverse through/ display all books
            System.out.println("\nAll Books:");
            for (Book book : books) {
                System.out.println(book);
            }
        }
    }

    private static void searchBookByTitle() {
        System.out.print("Enter title to search: ");
        String title = scanner.nextLine();
        //call the findBooksByTitle method of bookService to search book by its title from the list
        List<Book> books = bookService.findBooksByTitle(title);
        //check if the list is empty
        if (books.isEmpty()) {
            System.out.println("No books found.");
        } else {
            //otherwise iterate through and give the required book
            System.out.println("\nSearch Results:");
            for (Book book : books) {
                System.out.println(book);
            }
        }
    }

    private static void searchBookByAuthor() {
        System.out.print("Enter author to search: ");
        String author = scanner.nextLine();
        //call the findBooksByAuthor method of bookService to search book by its author from the list
        List<Book> books = bookService.findBooksByAuthor(author);
        // check if the list is empty
        if (books.isEmpty()) {
            System.out.println("No books found.");
        } else {
            //otherwise, iterate through and give the required book
            System.out.println("\nSearch Results:");
            for (Book book : books) {
                System.out.println(book);
            }
        }
    }

    private static void viewAvailableBooks() {
        //call the getAvailableBooks method of bookService to view the books in a list
        List<Book> books = bookService.getAvailableBooks();
        //check if it doesn't has book
        if (books.isEmpty()) {
            System.out.println("No books available.");
        } else {
            //otherwise, traverse through and show the books
            System.out.println("\nAvailable Books:");
            for (Book book : books) {
                System.out.println(book);
            }
        }
    }

    // USER OPERATIONS
    private static void userOperations() {
        while (true) {
            System.out.println("\n--- User Operations ---");
            System.out.println("1. Add User");
            System.out.println("2. View All Users");
            System.out.println("3. Update User");
            System.out.println("4. Delete User");
            System.out.println("5. Back to Main Menu");
            System.out.print("Enter choice: ");

            int choice = scanner.nextInt();
            scanner.nextLine();

            switch (choice) {
                case 1:
                    addNewUser();
                    break;
                case 2:
                    viewAllUsers();
                    break;
                case 3:
                    updateUser();
                    break;
                case 4:
                    deleteUser();
                    break;
                case 5:
                    return;
                default:
                    System.out.println("Invalid choice.");
            }
        }
    }

    private static void addNewUser() {
        System.out.print("Enter user name: ");
        String name = scanner.nextLine();
        System.out.print("Enter email: ");
        String email = scanner.nextLine();

        // creating a user object which consists of autogenerated-id ,name and email as an args
        User user = new User(IdGenerator.generateUserId(), name, email);
        //adding the user object using add method defined inside userService class
        userService.addUser(user);
        System.out.println("User added: " + user);
    }

    private static void viewAllUsers() {
        //fetch all users in a list calling getAllUsers method of userService
        List<User> users = userService.getAllUsers();
        if (users.isEmpty()) {
            System.out.println("No users found.");
        } else {
            System.out.println("\nAll Users:");
            for (User user : users) {
                System.out.println(user);
            }
        }

    }

    private static void updateUser() {

        //First show all users
        viewAllUsers();

        System.out.print("\nEnter User ID to update: ");
        String userId = scanner.nextLine();

        // Check if prompted user exists first by calling findUserById method of us
        User existingUser = userService.findUserById(userId);
        //if it doesn't show any results then error
        if (existingUser == null) {
            System.out.println("Error: User with ID " + userId + " not found.");
            return;
        }
        //otherwise shows the current details of that user
        System.out.println("\nCurrent User Details:");
        System.out.println(existingUser);

        // update the username
        System.out.print("\nEnter new name: ");
        String newName = scanner.nextLine();

        //update the email
        System.out.print("Enter new email: ");
        String newEmail = scanner.nextLine();

        // Only update fields that have new values set
        String finalName = newName.isBlank() ? existingUser.getName() : newName;
        String finalEmail = newEmail.isBlank() ? existingUser.getEmail() : newEmail;

        //set the new/final details calling updateUser method of us
        boolean isUpdated = userService.updateUser(userId, finalName, finalEmail);
        if (isUpdated) {
            System.out.println("\nUser updated successfully!");
            System.out.println("Updated Details:");
            //calling findUserById method of us to show updated details
            System.out.println(userService.findUserById(userId));
        } else {
            System.out.println("Error: Failed to update user.");
        }
    }

    private static void deleteUser() {
        // First show all users
        viewAllUsers();

        System.out.print("\nUser ID to delete: ");
        String userId = scanner.nextLine();

        // FIRST check if user exists
        User userToDelete = userService.findUserById(userId);
        if (userToDelete == null) {
            System.out.println("Error: User with ID " + userId + " does not exist!");
            return;
        }

        // show the user details before asking for confirmation
        System.out.println("\nUser to be deleted:");
        System.out.println(userToDelete);

        //ask for confirmation
        System.out.print("\nAre you sure you want to delete this user? (yes/no): ");
        String confirmation = scanner.nextLine().toLowerCase();

        if (confirmation.equals("yes")) {
            boolean isDeleted = userService.deleteUser(userId);
            if (isDeleted) {
                System.out.println("User deleted successfully!");
            } else {
                System.out.println("Error: Failed to delete user.");
            }
        } else {
            System.out.println("Deletion cancelled.");
        }
    }

    // TRANSACTION OPERATIONS
    private static void transactionOperations() {
        while (true) {
            System.out.println("\n--- Transaction Operations ---");
            System.out.println("1. Issue Book");
            System.out.println("2. Return Book");
            System.out.println("3. View All Transactions");
            System.out.println("4. Delete Transaction");
            System.out.println("5. Back to Main Menu");
            System.out.print("Enter choice: ");

            int choice = scanner.nextInt();
            scanner.nextLine();

            switch (choice) {
                case 1:
                    issueBook();
                    break;
                case 2:
                    returnBook();
                    break;
                case 3:
                    viewAllTransactions();
                    break;
                case 4:
                    deleteTransaction();
                    break;
                case 5:
                    return;
                default:
                    System.out.println("Invalid choice.");
            }
        }
    }

    private static void issueBook() {

        // first show available books calling getAvailableBooks() of bs
        List<Book> availableBooks = bookService.getAvailableBooks();
        //check if list is empty
        if (availableBooks.isEmpty()) {
            System.out.println("No books available.");
            return;
        }
        //otherwise show the available books
        System.out.println("\nAvailable Books:");
        for (Book book : availableBooks) {
            System.out.println(book);
        }

        // second show registered users calling getAllUsers() of us
        List<User> users = userService.getAllUsers();
        //check if list is empty
        if (users.isEmpty()) {
            System.out.println("No users registered.");
            return;
        }
        //otherwise show all registered users
        System.out.println("\nRegistered Users:");
        for (User user : users) {
            System.out.println(user);
        }


        //third get input of book id and user id to record the transaction
        System.out.print("\nEnter Book ID: ");
        String bookId = scanner.nextLine();
        System.out.print("Enter User ID: ");
        String userId = scanner.nextLine();

        //Call findBook & findUserById() of bs and us to check if they exists
        Book book = bookService.findBookById(bookId);
        User user = userService.findUserById(userId);

        //if shown empty throw a error message
        if (book == null || user == null) {
            System.out.println("Invalid book or user ID.");
            return;
        }

        // if book is not available
        if (!book.isAvailable()) {
            System.out.println("Book not available.");
            return;
        }


        // creating a transaction object which consists of autogenerated-id , book object , user object and current localdate as an args
        Transaction transaction = new Transaction(
                IdGenerator.generateTransactionId(),
                book,
                user,
                LocalDate.now()
        );

        //invoke issueBook() of ts to issue a book after all these process
        transactionService.issueBook(transaction);
        System.out.println("Book issued to Transaction ID: " + transaction.getId());
    }


    private static void returnBook() {
        //  Get active transactions
        List<Transaction> activeTransactions = transactionService.getActiveTransactions();

        //  Check if any active transactions exist
        if (activeTransactions.isEmpty()) {
            System.out.println("No active transactions available.");
            return;
        }

        //  Display active transactions
        System.out.println("\nActive Transactions:");
        for (Transaction t : activeTransactions) {
            System.out.println("ID: " + t.getId() +
                    " | Book: " + t.getBook().getTitle() +
                    " | User: " + t.getUser().getName());
        }

        //  Get transaction ID from user
        System.out.print("\nEnter Transaction ID to return: ");
        String transactionId = scanner.nextLine();

        //  Process return and show result
        if (transactionService.returnBook(transactionId)) {
            System.out.println("Book returned successfully!");
        } else {
            System.out.println("Error: Invalid Transaction ID or already returned.");
        }
    }

    private static void viewAllTransactions() {
        //fetch all transactions in a list calling getAllTransactions() of transService
        List<Transaction> transactions = transactionService.getAllTransactions();
        //check if empty
        if (transactions.isEmpty()) {
            System.out.println("No transactions.");
        }
        //otherwise list all of them
        else {
            System.out.println("\nAll Transactions:");
            for (Transaction t : transactions) {
                System.out.println(t);
            }
        }
    }

    private static void deleteTransaction() {
        //To delete first show all transactions
        viewAllTransactions();

        if (transactionService.getAllTransactions() != null) {
            return;
        }else{
            System.out.print("\nEnter Transaction ID to delete: ");
            String transactionId = scanner.nextLine();

            //invoke the deleteTransaction() of ts
            boolean deleted = transactionService.deleteTransaction(transactionId);
            //if deleted give success message
            if (deleted) {
                System.out.println("Transaction deleted successfully.");
            } else {
                System.out.println("Transaction not found.Try again");
            }
        }


    }

}